language: python
python:
  - "2.7"
  - "3.4"
matrix:
  allow_failures:
    - python: "2.7"
install:
  - pip install flake8 --use-mirrors
  - pip install pep8 --use-mirrors
  - pip install -q -e . --use-mirrors
addons:
  postgresql: "9.3"
before_script:
  - psql -c 'create database groovebox;' -U postgres
script:
  - nosetests
  - if [[ $TRAVIS_PYTHON_VERSION == '2.7' ]]; then flake8 groovebox; fi
cache: apt
